export {
  useCurrentUserQuery,
  useLoginMutation,
  useAdminLoginMutation,
  useRegisterMutation,
  useLogoutMutation,
  hydrateAuthSession,
} from '@/hooks/queries/use-auth-queries';

export {
  useProfileQuery,
  useUpdateProfileMutation,
  useUpdateSettingsMutation,
  useAccountStatsQuery,
  useOrdersQuery,
  useWishlistQuery,
  useSyncWishlistMutation,
  useToggleWishlistMutation,
  useRemoveWishlistMutation,
  useAddressesQuery,
  useCreateAddressMutation,
  useDeleteAddressMutation,
  useReviewsQuery,
  useCreateReviewMutation,
  useDeleteReviewMutation,
  useCouponsQuery,
  useNotificationsQuery,
  useMarkNotificationReadMutation,
  useMarkAllNotificationsReadMutation,
} from '@/hooks/queries/use-account-queries';

export {
  usePaymentConfigQuery,
  useCheckoutAddressesQuery,
  useCreateCheckoutAddressMutation,
  useOrderQuery,
  useVerifyOrderQuery,
  useCreateCheckoutMutation,
} from '@/hooks/queries/use-checkout-queries';

export {
  useAdminDashboardQuery,
  useAdminAnalyticsQuery,
  useAdminReportsQuery,
  useAdminOrdersQuery,
  useUpdateOrderStatusMutation,
  useAdminProductsQuery,
  useAdminCategoriesQuery,
  useCreateProductMutation,
  useUpdateProductMutation,
  useDeleteProductMutation,
  useSyncCatalogueMutation,
  useCreateCategoryMutation,
  useUpdateCategoryMutation,
  useDeleteCategoryMutation,
  useAdminUsersQuery,
  useUpdateUserMutation,
  useAdminInventoryQuery,
  useUpdateInventoryMutation,
  useAdminCouponsQuery,
  useCreateCouponMutation,
  useUpdateCouponMutation,
  useDeleteCouponMutation,
  useAdminReviewsQuery,
  useUpdateAdminReviewMutation,
  useDeleteAdminReviewMutation,
  useAdminBlogsQuery,
  useCreateBlogMutation,
  useUpdateBlogMutation,
  useDeleteBlogMutation,
  useAdminBannersQuery,
  useCreateBannerMutation,
  useUpdateBannerMutation,
  useDeleteBannerMutation,
} from '@/hooks/queries/use-admin-queries';
