export const routes = {
  home: '/',
  products: '/products',
  categories: '/categories',
  cart: '/cart',
  checkout: '/checkout',
  checkoutSuccess: '/checkout/success',
  checkoutFailure: '/checkout/failure',
  order: (orderNumber: string) => `/orders/${orderNumber}` as const,
  login: '/login',
  register: '/register',
  about: '/about',
  contact: '/contact',
  designSystem: '/design-system',
  account: {
    root: '/account',
    profile: '/account/profile',
    orders: '/account/orders',
    addresses: '/account/addresses',
    wishlist: '/account/wishlist',
    reviews: '/account/reviews',
    coupons: '/account/coupons',
    notifications: '/account/notifications',
    settings: '/account/settings',
  },
} as const;
